#!/bin/bash

echo "ext-zip              1.15.4   The zip PHP extension
ext-zlib             7.2.31   The zlib PHP extension (actual version: 7.2.31-1+ubuntu16.04.1+deb.sury.org+1)
lib-curl             7.47.0   The curl PHP library
php                  7.2.31   The PHP interpreter"